name: shinya
favicon: null
layout_spectrum: 0.04653212334960699
typography_spectrum: 0.4051138530485332
title: Shinya B by Shinya
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5074314612429589
  lightness: 0.40016874042339623
  saturation: 0.2970272602979094
  rhythmicContrast: 0.41787058883346617
purpose: []
